package com.great.entity;

public class AccountChar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_CHAR.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_CHAR.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer charNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_CHAR.ADM_UUID
     *
     * @return the value of ACCOUNT_CHAR.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmUuid() {
        return admUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_CHAR.ADM_UUID
     *
     * @param admUuid the value for ACCOUNT_CHAR.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmUuid(String admUuid) {
        this.admUuid = admUuid == null ? null : admUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_CHAR.CHAR_NO
     *
     * @return the value of ACCOUNT_CHAR.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getCharNo() {
        return charNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_CHAR.CHAR_NO
     *
     * @param charNo the value for ACCOUNT_CHAR.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCharNo(Integer charNo) {
        this.charNo = charNo;
    }
}