package com.great.entity;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer authNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY.AUTH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY.AUTH_PARENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer authParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY.MENU_URL
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String menuUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY.AUTH_NO
     *
     * @return the value of AUTHORITY.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getAuthNo() {
        return authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY.AUTH_NO
     *
     * @param authNo the value for AUTHORITY.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAuthNo(Integer authNo) {
        this.authNo = authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY.AUTH_NAME
     *
     * @return the value of AUTHORITY.AUTH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY.AUTH_NAME
     *
     * @param authName the value for AUTHORITY.AUTH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY.AUTH_PARENT
     *
     * @return the value of AUTHORITY.AUTH_PARENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getAuthParent() {
        return authParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY.AUTH_PARENT
     *
     * @param authParent the value for AUTHORITY.AUTH_PARENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAuthParent(Integer authParent) {
        this.authParent = authParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY.MENU_URL
     *
     * @return the value of AUTHORITY.MENU_URL
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY.MENU_URL
     *
     * @param menuUrl the value for AUTHORITY.MENU_URL
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }
}