package com.great.entity;

import java.util.Date;

public class CenterAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ANNOUNCEMENT.CA_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer caNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ANNOUNCEMENT.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ANNOUNCEMENT.CA_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date caDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ANNOUNCEMENT.CA_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String caContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ANNOUNCEMENT.CA_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String caTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ANNOUNCEMENT.CA_NO
     *
     * @return the value of CENTER_ANNOUNCEMENT.CA_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getCaNo() {
        return caNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ANNOUNCEMENT.CA_NO
     *
     * @param caNo the value for CENTER_ANNOUNCEMENT.CA_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCaNo(Integer caNo) {
        this.caNo = caNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ANNOUNCEMENT.ADM_UUID
     *
     * @return the value of CENTER_ANNOUNCEMENT.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmUuid() {
        return admUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ANNOUNCEMENT.ADM_UUID
     *
     * @param admUuid the value for CENTER_ANNOUNCEMENT.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmUuid(String admUuid) {
        this.admUuid = admUuid == null ? null : admUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ANNOUNCEMENT.CA_DATE
     *
     * @return the value of CENTER_ANNOUNCEMENT.CA_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getCaDate() {
        return caDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ANNOUNCEMENT.CA_DATE
     *
     * @param caDate the value for CENTER_ANNOUNCEMENT.CA_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCaDate(Date caDate) {
        this.caDate = caDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ANNOUNCEMENT.CA_CONTEXT
     *
     * @return the value of CENTER_ANNOUNCEMENT.CA_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getCaContext() {
        return caContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ANNOUNCEMENT.CA_CONTEXT
     *
     * @param caContext the value for CENTER_ANNOUNCEMENT.CA_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCaContext(String caContext) {
        this.caContext = caContext == null ? null : caContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ANNOUNCEMENT.CA_TITLE
     *
     * @return the value of CENTER_ANNOUNCEMENT.CA_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getCaTitle() {
        return caTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ANNOUNCEMENT.CA_TITLE
     *
     * @param caTitle the value for CENTER_ANNOUNCEMENT.CA_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCaTitle(String caTitle) {
        this.caTitle = caTitle == null ? null : caTitle.trim();
    }

	@Override
	public String toString() {
		return "CenterAnnouncement [caNo=" + caNo + ", admUuid=" + admUuid
				+ ", caDate=" + caDate + ", caContext=" + caContext
				+ ", caTitle=" + caTitle + "]";
	}
    
    

}