package com.great.entity;

import java.util.Date;

public class CenterAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.ADM_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer admId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.ADM_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.ADM_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.ADM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date admDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CENTER_ADMIN.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.ADM_UUID
     *
     * @return the value of CENTER_ADMIN.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmUuid() {
        return admUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.ADM_UUID
     *
     * @param admUuid the value for CENTER_ADMIN.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmUuid(String admUuid) {
        this.admUuid = admUuid == null ? null : admUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.ADM_ID
     *
     * @return the value of CENTER_ADMIN.ADM_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getAdmId() {
        return admId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.ADM_ID
     *
     * @param admId the value for CENTER_ADMIN.ADM_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmId(Integer admId) {
        this.admId = admId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.ADM_NAME
     *
     * @return the value of CENTER_ADMIN.ADM_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmName() {
        return admName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.ADM_NAME
     *
     * @param admName the value for CENTER_ADMIN.ADM_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmName(String admName) {
        this.admName = admName == null ? null : admName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.ADM_PWD
     *
     * @return the value of CENTER_ADMIN.ADM_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmPwd() {
        return admPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.ADM_PWD
     *
     * @param admPwd the value for CENTER_ADMIN.ADM_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmPwd(String admPwd) {
        this.admPwd = admPwd == null ? null : admPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.ADM_DATE
     *
     * @return the value of CENTER_ADMIN.ADM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getAdmDate() {
        return admDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.ADM_DATE
     *
     * @param admDate the value for CENTER_ADMIN.ADM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmDate(Date admDate) {
        this.admDate = admDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTER_ADMIN.LAST_LOGIN_DATE
     *
     * @return the value of CENTER_ADMIN.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTER_ADMIN.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for CENTER_ADMIN.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

	@Override
	public String toString() {
		return "CenterAdmin [admUuid=" + admUuid + ", admId=" + admId
				+ ", admName=" + admName + ", admPwd=" + admPwd + ", admDate="
				+ admDate + ", lastLoginDate=" + lastLoginDate + "]";
	}

	
    
}