package com.great.entity;

public class CharAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAR_AUTH.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer charNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAR_AUTH.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer authNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAR_AUTH.CHAR_NO
     *
     * @return the value of CHAR_AUTH.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getCharNo() {
        return charNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAR_AUTH.CHAR_NO
     *
     * @param charNo the value for CHAR_AUTH.CHAR_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCharNo(Integer charNo) {
        this.charNo = charNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAR_AUTH.AUTH_NO
     *
     * @return the value of CHAR_AUTH.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getAuthNo() {
        return authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAR_AUTH.AUTH_NO
     *
     * @param authNo the value for CHAR_AUTH.AUTH_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAuthNo(Integer authNo) {
        this.authNo = authNo;
    }
}