package com.great.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DriverSchool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer schId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private BigDecimal schScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.SCH_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DRIVER_SCHOOL.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_UUID
     *
     * @return the value of DRIVER_SCHOOL.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchUuid() {
        return schUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_UUID
     *
     * @param schUuid the value for DRIVER_SCHOOL.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchUuid(String schUuid) {
        this.schUuid = schUuid == null ? null : schUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_ID
     *
     * @return the value of DRIVER_SCHOOL.SCH_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSchId() {
        return schId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_ID
     *
     * @param schId the value for DRIVER_SCHOOL.SCH_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchId(Integer schId) {
        this.schId = schId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_NAME
     *
     * @return the value of DRIVER_SCHOOL.SCH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchName() {
        return schName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_NAME
     *
     * @param schName the value for DRIVER_SCHOOL.SCH_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchName(String schName) {
        this.schName = schName == null ? null : schName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_PWD
     *
     * @return the value of DRIVER_SCHOOL.SCH_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchPwd() {
        return schPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_PWD
     *
     * @param schPwd the value for DRIVER_SCHOOL.SCH_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchPwd(String schPwd) {
        this.schPwd = schPwd == null ? null : schPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_INTRO
     *
     * @return the value of DRIVER_SCHOOL.SCH_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchIntro() {
        return schIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_INTRO
     *
     * @param schIntro the value for DRIVER_SCHOOL.SCH_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchIntro(String schIntro) {
        this.schIntro = schIntro == null ? null : schIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_SCORE
     *
     * @return the value of DRIVER_SCHOOL.SCH_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public BigDecimal getSchScore() {
        return schScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_SCORE
     *
     * @param schScore the value for DRIVER_SCHOOL.SCH_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchScore(BigDecimal schScore) {
        this.schScore = schScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.CREATE_DATE
     *
     * @return the value of DRIVER_SCHOOL.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.CREATE_DATE
     *
     * @param createDate the value for DRIVER_SCHOOL.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_LOCATION
     *
     * @return the value of DRIVER_SCHOOL.SCH_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchLocation() {
        return schLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_LOCATION
     *
     * @param schLocation the value for DRIVER_SCHOOL.SCH_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchLocation(String schLocation) {
        this.schLocation = schLocation == null ? null : schLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.SCH_PHONE
     *
     * @return the value of DRIVER_SCHOOL.SCH_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchPhone() {
        return schPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.SCH_PHONE
     *
     * @param schPhone the value for DRIVER_SCHOOL.SCH_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchPhone(String schPhone) {
        this.schPhone = schPhone == null ? null : schPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DRIVER_SCHOOL.LAST_LOGIN_DATE
     *
     * @return the value of DRIVER_SCHOOL.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DRIVER_SCHOOL.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for DRIVER_SCHOOL.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

	@Override
	public String toString() {
		return "DriverSchool [schUuid=" + schUuid + ", schId=" + schId
				+ ", schName=" + schName + ", schPwd=" + schPwd + ", schIntro="
				+ schIntro + ", schScore=" + schScore + ", createDate="
				+ createDate + ", schLocation=" + schLocation + ", schPhone="
				+ schPhone + ", lastLoginDate=" + lastLoginDate + "]";
	}
    
}