package com.great.entity;

import java.util.Date;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String examUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String admUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String examLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date examDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_MAX_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer examMaxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String examSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_CUR_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer examCurNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXAM.EXAM_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String examStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_UUID
     *
     * @return the value of EXAM.EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getExamUuid() {
        return examUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_UUID
     *
     * @param examUuid the value for EXAM.EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamUuid(String examUuid) {
        this.examUuid = examUuid == null ? null : examUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.ADM_UUID
     *
     * @return the value of EXAM.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAdmUuid() {
        return admUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.ADM_UUID
     *
     * @param admUuid the value for EXAM.ADM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAdmUuid(String admUuid) {
        this.admUuid = admUuid == null ? null : admUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_LOCATION
     *
     * @return the value of EXAM.EXAM_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getExamLocation() {
        return examLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_LOCATION
     *
     * @param examLocation the value for EXAM.EXAM_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamLocation(String examLocation) {
        this.examLocation = examLocation == null ? null : examLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_DATE
     *
     * @return the value of EXAM.EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_DATE
     *
     * @param examDate the value for EXAM.EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_MAX_NUM
     *
     * @return the value of EXAM.EXAM_MAX_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getExamMaxNum() {
        return examMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_MAX_NUM
     *
     * @param examMaxNum the value for EXAM.EXAM_MAX_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamMaxNum(Integer examMaxNum) {
        this.examMaxNum = examMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_SUB
     *
     * @return the value of EXAM.EXAM_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getExamSub() {
        return examSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_SUB
     *
     * @param examSub the value for EXAM.EXAM_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamSub(String examSub) {
        this.examSub = examSub == null ? null : examSub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_CUR_NUM
     *
     * @return the value of EXAM.EXAM_CUR_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getExamCurNum() {
        return examCurNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_CUR_NUM
     *
     * @param examCurNum the value for EXAM.EXAM_CUR_NUM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamCurNum(Integer examCurNum) {
        this.examCurNum = examCurNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXAM.EXAM_STATUS
     *
     * @return the value of EXAM.EXAM_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getExamStatus() {
        return examStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXAM.EXAM_STATUS
     *
     * @param examStatus the value for EXAM.EXAM_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setExamStatus(String examStatus) {
        this.examStatus = examStatus == null ? null : examStatus.trim();
    }

	@Override
	public String toString() {
		return "Exam [examUuid=" + examUuid + ", admUuid=" + admUuid
				+ ", examLocation=" + examLocation + ", examDate=" + examDate
				+ ", examMaxNum=" + examMaxNum + ", examSub=" + examSub
				+ ", examCurNum=" + examCurNum + ", examStatus=" + examStatus
				+ "]";
	}
    
}