package com.great.entity;

public class PracticeNoRec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRACTICE_NO_REC.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRACTICE_NO_REC.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer qNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRACTICE_NO_REC.STU_UUID
     *
     * @return the value of PRACTICE_NO_REC.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRACTICE_NO_REC.STU_UUID
     *
     * @param stuUuid the value for PRACTICE_NO_REC.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRACTICE_NO_REC.Q_NO
     *
     * @return the value of PRACTICE_NO_REC.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getqNo() {
        return qNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRACTICE_NO_REC.Q_NO
     *
     * @param qNo the value for PRACTICE_NO_REC.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqNo(Integer qNo) {
        this.qNo = qNo;
    }
}