package com.great.entity;

public class QuestionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TYPE.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer tNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TYPE.T_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TYPE.T_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer tScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TYPE.T_NO
     *
     * @return the value of QUESTION_TYPE.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer gettNo() {
        return tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TYPE.T_NO
     *
     * @param tNo the value for QUESTION_TYPE.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void settNo(Integer tNo) {
        this.tNo = tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TYPE.T_NAME
     *
     * @return the value of QUESTION_TYPE.T_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TYPE.T_NAME
     *
     * @param tName the value for QUESTION_TYPE.T_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TYPE.T_SCORE
     *
     * @return the value of QUESTION_TYPE.T_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer gettScore() {
        return tScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TYPE.T_SCORE
     *
     * @param tScore the value for QUESTION_TYPE.T_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void settScore(Integer tScore) {
        this.tScore = tScore;
    }
}