package com.great.entity;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer qNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer tNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_DESCRIPTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_ANSWER_A
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qAnswerA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_ANSWER_B
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qAnswerB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_ANSWER_C
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qAnswerC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_ANSWER_D
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qAnswerD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_ANSWER_CORRECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qAnswerCorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.Q_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String qSubject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_NO
     *
     * @return the value of QUESTION.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getqNo() {
        return qNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_NO
     *
     * @param qNo the value for QUESTION.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqNo(Integer qNo) {
        this.qNo = qNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.T_NO
     *
     * @return the value of QUESTION.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer gettNo() {
        return tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.T_NO
     *
     * @param tNo the value for QUESTION.T_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void settNo(Integer tNo) {
        this.tNo = tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_DESCRIPTION
     *
     * @return the value of QUESTION.Q_DESCRIPTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqDescription() {
        return qDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_DESCRIPTION
     *
     * @param qDescription the value for QUESTION.Q_DESCRIPTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqDescription(String qDescription) {
        this.qDescription = qDescription == null ? null : qDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_ANSWER_A
     *
     * @return the value of QUESTION.Q_ANSWER_A
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqAnswerA() {
        return qAnswerA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_ANSWER_A
     *
     * @param qAnswerA the value for QUESTION.Q_ANSWER_A
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqAnswerA(String qAnswerA) {
        this.qAnswerA = qAnswerA == null ? null : qAnswerA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_ANSWER_B
     *
     * @return the value of QUESTION.Q_ANSWER_B
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqAnswerB() {
        return qAnswerB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_ANSWER_B
     *
     * @param qAnswerB the value for QUESTION.Q_ANSWER_B
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqAnswerB(String qAnswerB) {
        this.qAnswerB = qAnswerB == null ? null : qAnswerB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_ANSWER_C
     *
     * @return the value of QUESTION.Q_ANSWER_C
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqAnswerC() {
        return qAnswerC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_ANSWER_C
     *
     * @param qAnswerC the value for QUESTION.Q_ANSWER_C
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqAnswerC(String qAnswerC) {
        this.qAnswerC = qAnswerC == null ? null : qAnswerC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_ANSWER_D
     *
     * @return the value of QUESTION.Q_ANSWER_D
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqAnswerD() {
        return qAnswerD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_ANSWER_D
     *
     * @param qAnswerD the value for QUESTION.Q_ANSWER_D
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqAnswerD(String qAnswerD) {
        this.qAnswerD = qAnswerD == null ? null : qAnswerD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_ANSWER_CORRECT
     *
     * @return the value of QUESTION.Q_ANSWER_CORRECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqAnswerCorrect() {
        return qAnswerCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_ANSWER_CORRECT
     *
     * @param qAnswerCorrect the value for QUESTION.Q_ANSWER_CORRECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqAnswerCorrect(String qAnswerCorrect) {
        this.qAnswerCorrect = qAnswerCorrect == null ? null : qAnswerCorrect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.Q_SUBJECT
     *
     * @return the value of QUESTION.Q_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getqSubject() {
        return qSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.Q_SUBJECT
     *
     * @param qSubject the value for QUESTION.Q_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqSubject(String qSubject) {
        this.qSubject = qSubject == null ? null : qSubject.trim();
    }

	@Override
	public String toString() {
		return "Question [qNo=" + qNo + ", tNo=" + tNo + ", qDescription="
				+ qDescription + ", qAnswerA=" + qAnswerA + ", qAnswerB="
				+ qAnswerB + ", qAnswerC=" + qAnswerC + ", qAnswerD="
				+ qAnswerD + ", qAnswerCorrect=" + qAnswerCorrect
				+ ", qSubject=" + qSubject + "]";
	}
    
    
}