package com.great.entity;

import java.util.Date;

public class SchAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCH_ANNOUNCEMENT.AN_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String anUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCH_ANNOUNCEMENT.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCH_ANNOUNCEMENT.AN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date anDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCH_ANNOUNCEMENT.AN_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String anContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCH_ANNOUNCEMENT.AN_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String anTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCH_ANNOUNCEMENT.AN_UUID
     *
     * @return the value of SCH_ANNOUNCEMENT.AN_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAnUuid() {
        return anUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCH_ANNOUNCEMENT.AN_UUID
     *
     * @param anUuid the value for SCH_ANNOUNCEMENT.AN_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAnUuid(String anUuid) {
        this.anUuid = anUuid == null ? null : anUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCH_ANNOUNCEMENT.SCH_UUID
     *
     * @return the value of SCH_ANNOUNCEMENT.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchUuid() {
        return schUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCH_ANNOUNCEMENT.SCH_UUID
     *
     * @param schUuid the value for SCH_ANNOUNCEMENT.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchUuid(String schUuid) {
        this.schUuid = schUuid == null ? null : schUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCH_ANNOUNCEMENT.AN_DATE
     *
     * @return the value of SCH_ANNOUNCEMENT.AN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getAnDate() {
        return anDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCH_ANNOUNCEMENT.AN_DATE
     *
     * @param anDate the value for SCH_ANNOUNCEMENT.AN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAnDate(Date anDate) {
        this.anDate = anDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCH_ANNOUNCEMENT.AN_CONTEXT
     *
     * @return the value of SCH_ANNOUNCEMENT.AN_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAnContext() {
        return anContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCH_ANNOUNCEMENT.AN_CONTEXT
     *
     * @param anContext the value for SCH_ANNOUNCEMENT.AN_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAnContext(String anContext) {
        this.anContext = anContext == null ? null : anContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCH_ANNOUNCEMENT.AN_TITLE
     *
     * @return the value of SCH_ANNOUNCEMENT.AN_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAnTitle() {
        return anTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCH_ANNOUNCEMENT.AN_TITLE
     *
     * @param anTitle the value for SCH_ANNOUNCEMENT.AN_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAnTitle(String anTitle) {
        this.anTitle = anTitle == null ? null : anTitle.trim();
    }
}