package com.great.entity;

import java.util.Date;

public class SchoolMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date scmsgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_MSG.SCMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scmsgGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_UUID
     *
     * @return the value of SCHOOL_MSG.SCMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */

    public String getScmsgUuid() {
        return scmsgUuid;
    }

    public SchoolMsg() {
		super();
	}

	public SchoolMsg(String scmsgUuid, String schUuid, String scmsgTitle,
			String scmsgContext, String scmsgIdentity, Date scmsgDate,
			String scmsgStatus, String scmsgType, String scmsgGroup) {
		super();
		this.scmsgUuid = scmsgUuid;
		this.schUuid = schUuid;
		this.scmsgTitle = scmsgTitle;
		this.scmsgContext = scmsgContext;
		this.scmsgIdentity = scmsgIdentity;
		this.scmsgDate = scmsgDate;
		this.scmsgStatus = scmsgStatus;
		this.scmsgType = scmsgType;
		this.scmsgGroup = scmsgGroup;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_UUID
     *
     * @param scmsgUuid the value for SCHOOL_MSG.SCMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgUuid(String scmsgUuid) {
        this.scmsgUuid = scmsgUuid == null ? null : scmsgUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCH_UUID
     *
     * @return the value of SCHOOL_MSG.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchUuid() {
        return schUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCH_UUID
     *
     * @param schUuid the value for SCHOOL_MSG.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchUuid(String schUuid) {
        this.schUuid = schUuid == null ? null : schUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_TITLE
     *
     * @return the value of SCHOOL_MSG.SCMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgTitle() {
        return scmsgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_TITLE
     *
     * @param scmsgTitle the value for SCHOOL_MSG.SCMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgTitle(String scmsgTitle) {
        this.scmsgTitle = scmsgTitle == null ? null : scmsgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_CONTEXT
     *
     * @return the value of SCHOOL_MSG.SCMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgContext() {
        return scmsgContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_CONTEXT
     *
     * @param scmsgContext the value for SCHOOL_MSG.SCMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgContext(String scmsgContext) {
        this.scmsgContext = scmsgContext == null ? null : scmsgContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_IDENTITY
     *
     * @return the value of SCHOOL_MSG.SCMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgIdentity() {
        return scmsgIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_IDENTITY
     *
     * @param scmsgIdentity the value for SCHOOL_MSG.SCMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgIdentity(String scmsgIdentity) {
        this.scmsgIdentity = scmsgIdentity == null ? null : scmsgIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_DATE
     *
     * @return the value of SCHOOL_MSG.SCMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getScmsgDate() {
        return scmsgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_DATE
     *
     * @param scmsgDate the value for SCHOOL_MSG.SCMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgDate(Date scmsgDate) {
        this.scmsgDate = scmsgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_STATUS
     *
     * @return the value of SCHOOL_MSG.SCMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgStatus() {
        return scmsgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_STATUS
     *
     * @param scmsgStatus the value for SCHOOL_MSG.SCMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgStatus(String scmsgStatus) {
        this.scmsgStatus = scmsgStatus == null ? null : scmsgStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_TYPE
     *
     * @return the value of SCHOOL_MSG.SCMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgType() {
        return scmsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_TYPE
     *
     * @param scmsgType the value for SCHOOL_MSG.SCMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgType(String scmsgType) {
        this.scmsgType = scmsgType == null ? null : scmsgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_MSG.SCMSG_GROUP
     *
     * @return the value of SCHOOL_MSG.SCMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScmsgGroup() {
        return scmsgGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_MSG.SCMSG_GROUP
     *
     * @param scmsgGroup the value for SCHOOL_MSG.SCMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScmsgGroup(String scmsgGroup) {
        this.scmsgGroup = scmsgGroup == null ? null : scmsgGroup.trim();
    }

	@Override
	public String toString() {
		return "SchoolMsg [scmsgUuid=" + scmsgUuid + ", schUuid=" + schUuid
				+ ", scmsgTitle=" + scmsgTitle + ", scmsgContext="
				+ scmsgContext + ", scmsgIdentity=" + scmsgIdentity
				+ ", scmsgDate=" + scmsgDate + ", scmsgStatus=" + scmsgStatus
				+ ", scmsgType=" + scmsgType + ", scmsgGroup=" + scmsgGroup
				+ "]";
	}
    
    
    
    
}