package com.great.entity;

import java.util.Date;

public class SchoolStu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.SCH_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schStuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.SCH_STU_PERIODS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer schStuPeriods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.SCH_STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schStuStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date graduatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.SCH_STU_UUID
     *
     * @return the value of SCHOOL_STU.SCH_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    
    
    
    public String getSchStuUuid() {
        return schStuUuid;
    }

    public SchoolStu() {
		super();
	}

	public SchoolStu(String schStuUuid, String schUuid, String stuUuid,
			Integer schStuPeriods, String schStuStatus, Date registerDate,
			Date graduatedDate) {
		super();
		this.schStuUuid = schStuUuid;
		this.schUuid = schUuid;
		this.stuUuid = stuUuid;
		this.schStuPeriods = schStuPeriods;
		this.schStuStatus = schStuStatus;
		this.registerDate = registerDate;
		this.graduatedDate = graduatedDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.SCH_STU_UUID
     *
     * @param schStuUuid the value for SCHOOL_STU.SCH_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchStuUuid(String schStuUuid) {
        this.schStuUuid = schStuUuid == null ? null : schStuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.SCH_UUID
     *
     * @return the value of SCHOOL_STU.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchUuid() {
        return schUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.SCH_UUID
     *
     * @param schUuid the value for SCHOOL_STU.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchUuid(String schUuid) {
        this.schUuid = schUuid == null ? null : schUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.STU_UUID
     *
     * @return the value of SCHOOL_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.STU_UUID
     *
     * @param stuUuid the value for SCHOOL_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.SCH_STU_PERIODS
     *
     * @return the value of SCHOOL_STU.SCH_STU_PERIODS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSchStuPeriods() {
        return schStuPeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.SCH_STU_PERIODS
     *
     * @param schStuPeriods the value for SCHOOL_STU.SCH_STU_PERIODS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchStuPeriods(Integer schStuPeriods) {
        this.schStuPeriods = schStuPeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.SCH_STU_STATUS
     *
     * @return the value of SCHOOL_STU.SCH_STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchStuStatus() {
        return schStuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.SCH_STU_STATUS
     *
     * @param schStuStatus the value for SCHOOL_STU.SCH_STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchStuStatus(String schStuStatus) {
        this.schStuStatus = schStuStatus == null ? null : schStuStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.REGISTER_DATE
     *
     * @return the value of SCHOOL_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.REGISTER_DATE
     *
     * @param registerDate the value for SCHOOL_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL_STU.GRADUATED_DATE
     *
     * @return the value of SCHOOL_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getGraduatedDate() {
        return graduatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL_STU.GRADUATED_DATE
     *
     * @param graduatedDate the value for SCHOOL_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setGraduatedDate(Date graduatedDate) {
        this.graduatedDate = graduatedDate;
    }
}