package com.great.entity;

public class StimulatAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STIMULAT_ANSWER.S_ANS_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String sAnsUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STIMULAT_ANSWER.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STIMULAT_ANSWER.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer qNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STIMULAT_ANSWER.ANSWER_CHOICE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String answerChoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STIMULAT_ANSWER.S_ANS_UUID
     *
     * @return the value of STIMULAT_ANSWER.S_ANS_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getsAnsUuid() {
        return sAnsUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STIMULAT_ANSWER.S_ANS_UUID
     *
     * @param sAnsUuid the value for STIMULAT_ANSWER.S_ANS_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setsAnsUuid(String sAnsUuid) {
        this.sAnsUuid = sAnsUuid == null ? null : sAnsUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STIMULAT_ANSWER.STU_UUID
     *
     * @return the value of STIMULAT_ANSWER.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STIMULAT_ANSWER.STU_UUID
     *
     * @param stuUuid the value for STIMULAT_ANSWER.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STIMULAT_ANSWER.Q_NO
     *
     * @return the value of STIMULAT_ANSWER.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getqNo() {
        return qNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STIMULAT_ANSWER.Q_NO
     *
     * @param qNo the value for STIMULAT_ANSWER.Q_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setqNo(Integer qNo) {
        this.qNo = qNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STIMULAT_ANSWER.ANSWER_CHOICE
     *
     * @return the value of STIMULAT_ANSWER.ANSWER_CHOICE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getAnswerChoice() {
        return answerChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STIMULAT_ANSWER.ANSWER_CHOICE
     *
     * @param answerChoice the value for STIMULAT_ANSWER.ANSWER_CHOICE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setAnswerChoice(String answerChoice) {
        this.answerChoice = answerChoice == null ? null : answerChoice.trim();
    }
}