package com.great.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer subNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
  
    private Date stuBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STU_CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuCurSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String drivingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.FORMER_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String formerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.ETHNIC_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String ethnicGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.CUR_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String curLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.IDENTITY_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String identityLocation;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column STUDENT.STU_NAME
	 *
	 * @mbggenerated Tue Sep 26 17:46:16 CST 2017
	 */
	private String stuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_UUID
     *
     * @return the value of STUDENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
	
	public Student() {
		super();
	}
	
	
	
	
    public Student(String stuUuid, Integer subNo, Integer stuId,
			Date stuBirthday, String stuGender, String stuPwd,
			String stuIdentity, String stuPhone, Date createDate,
			String stuCurSub, String drivingType, String formerType,
			String ethnicGroup, String curLocation, String identityLocation,
			String stuName) {
		super();
		this.stuUuid = stuUuid;
		this.subNo = subNo;
		this.stuId = stuId;
		this.stuBirthday = stuBirthday;
		this.stuGender = stuGender;
		this.stuPwd = stuPwd;
		this.stuIdentity = stuIdentity;
		this.stuPhone = stuPhone;
		this.createDate = createDate;
		this.stuCurSub = stuCurSub;
		this.drivingType = drivingType;
		this.formerType = formerType;
		this.ethnicGroup = ethnicGroup;
		this.curLocation = curLocation;
		this.identityLocation = identityLocation;
		this.stuName = stuName;
	}




	public String getStuUuid() {
        return stuUuid;
    }


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_UUID
     *
     * @param stuUuid the value for STUDENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.SUB_NO
     *
     * @return the value of STUDENT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSubNo() {
        return subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.SUB_NO
     *
     * @param subNo the value for STUDENT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSubNo(Integer subNo) {
        this.subNo = subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_ID
     *
     * @return the value of STUDENT.STU_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_ID
     *
     * @param stuId the value for STUDENT.STU_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_NAME
     *
     * @return the value of STUDENT.STU_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_NAME
     *
     * @param stuName the value for STUDENT.STU_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_BIRTHDAY
     *
     * @return the value of STUDENT.STU_BIRTHDAY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getStuBirthday() {
        return stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_BIRTHDAY
     *
     * @param stuBirthday the value for STUDENT.STU_BIRTHDAY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    
    
    
    
    
    public void setStuBirthday(Date stuBirthday) {
        this.stuBirthday = stuBirthday;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_GENDER
     *
     * @return the value of STUDENT.STU_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_GENDER
     *
     * @param stuGender the value for STUDENT.STU_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_PWD
     *
     * @return the value of STUDENT.STU_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuPwd() {
        return stuPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_PWD
     *
     * @param stuPwd the value for STUDENT.STU_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuPwd(String stuPwd) {
        this.stuPwd = stuPwd == null ? null : stuPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_IDENTITY
     *
     * @return the value of STUDENT.STU_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuIdentity() {
        return stuIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_IDENTITY
     *
     * @param stuIdentity the value for STUDENT.STU_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuIdentity(String stuIdentity) {
        this.stuIdentity = stuIdentity == null ? null : stuIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_PHONE
     *
     * @return the value of STUDENT.STU_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_PHONE
     *
     * @param stuPhone the value for STUDENT.STU_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.CREATE_DATE
     *
     * @return the value of STUDENT.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.CREATE_DATE
     *
     * @param createDate the value for STUDENT.CREATE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STU_CUR_SUB
     *
     * @return the value of STUDENT.STU_CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuCurSub() {
        return stuCurSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STU_CUR_SUB
     *
     * @param stuCurSub the value for STUDENT.STU_CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuCurSub(String stuCurSub) {
        this.stuCurSub = stuCurSub == null ? null : stuCurSub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.DRIVING_TYPE
     *
     * @return the value of STUDENT.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getDrivingType() {
        return drivingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.DRIVING_TYPE
     *
     * @param drivingType the value for STUDENT.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setDrivingType(String drivingType) {
        this.drivingType = drivingType == null ? null : drivingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.FORMER_TYPE
     *
     * @return the value of STUDENT.FORMER_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getFormerType() {
        return formerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.FORMER_TYPE
     *
     * @param formerType the value for STUDENT.FORMER_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setFormerType(String formerType) {
        this.formerType = formerType == null ? null : formerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.ETHNIC_GROUP
     *
     * @return the value of STUDENT.ETHNIC_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.ETHNIC_GROUP
     *
     * @param ethnicGroup the value for STUDENT.ETHNIC_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setEthnicGroup(String ethnicGroup) {
        this.ethnicGroup = ethnicGroup == null ? null : ethnicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.CUR_LOCATION
     *
     * @return the value of STUDENT.CUR_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getCurLocation() {
        return curLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.CUR_LOCATION
     *
     * @param curLocation the value for STUDENT.CUR_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCurLocation(String curLocation) {
        this.curLocation = curLocation == null ? null : curLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.IDENTITY_LOCATION
     *
     * @return the value of STUDENT.IDENTITY_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getIdentityLocation() {
        return identityLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.IDENTITY_LOCATION
     *
     * @param identityLocation the value for STUDENT.IDENTITY_LOCATION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setIdentityLocation(String identityLocation) {
        this.identityLocation = identityLocation == null ? null : identityLocation.trim();
    }

	@Override
	public String toString() {
		return "Student [stuUuid=" + stuUuid + ", subNo=" + subNo + ", stuId="
				+ stuId + ", stuName=" + stuName + ", stuBirthday="
				+ stuBirthday + ", stuGender=" + stuGender + ", stuPwd="
				+ stuPwd + ", stuIdentity=" + stuIdentity + ", stuPhone="
				+ stuPhone + ", createDate=" + createDate + ", stuCurSub="
				+ stuCurSub + ", drivingType=" + drivingType + ", formerType="
				+ formerType + ", ethnicGroup=" + ethnicGroup
				+ ", curLocation=" + curLocation + ", identityLocation="
				+ identityLocation + "]";
	}
    
    
}