package com.great.entity;

import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class StuMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date smsgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_MSG.SMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String smsgGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_UUID
     *
     * @return the value of STU_MSG.SMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgUuid() {
        return smsgUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_UUID
     *
     * @param smsgUuid the value for STU_MSG.SMSG_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgUuid(String smsgUuid) {
        this.smsgUuid = smsgUuid == null ? null : smsgUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.STU_UUID
     *
     * @return the value of STU_MSG.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.STU_UUID
     *
     * @param stuUuid the value for STU_MSG.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    
    
    
    
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    public StuMsg() {
		super();
	}

	public StuMsg(String smsgUuid, String stuUuid, String smsgTitle,
			String smsgContext, String smsgIdentity, Date smsgDate,
			String smsgStatus, String smsgType, String smsgGroup) {
		super();
		this.smsgUuid = smsgUuid;
		this.stuUuid = stuUuid;
		this.smsgTitle = smsgTitle;
		this.smsgContext = smsgContext;
		this.smsgIdentity = smsgIdentity;
		this.smsgDate = smsgDate;
		this.smsgStatus = smsgStatus;
		this.smsgType = smsgType;
		this.smsgGroup = smsgGroup;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_TITLE
     *
     * @return the value of STU_MSG.SMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgTitle() {
        return smsgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_TITLE
     *
     * @param smsgTitle the value for STU_MSG.SMSG_TITLE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgTitle(String smsgTitle) {
        this.smsgTitle = smsgTitle == null ? null : smsgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_CONTEXT
     *
     * @return the value of STU_MSG.SMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgContext() {
        return smsgContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_CONTEXT
     *
     * @param smsgContext the value for STU_MSG.SMSG_CONTEXT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgContext(String smsgContext) {
        this.smsgContext = smsgContext == null ? null : smsgContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_IDENTITY
     *
     * @return the value of STU_MSG.SMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgIdentity() {
        return smsgIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_IDENTITY
     *
     * @param smsgIdentity the value for STU_MSG.SMSG_IDENTITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgIdentity(String smsgIdentity) {
        this.smsgIdentity = smsgIdentity == null ? null : smsgIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_DATE
     *
     * @return the value of STU_MSG.SMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getSmsgDate() {
        return smsgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_DATE
     *
     * @param smsgDate the value for STU_MSG.SMSG_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgDate(Date smsgDate) {
        this.smsgDate = smsgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_STATUS
     *
     * @return the value of STU_MSG.SMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgStatus() {
        return smsgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_STATUS
     *
     * @param smsgStatus the value for STU_MSG.SMSG_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgStatus(String smsgStatus) {
        this.smsgStatus = smsgStatus == null ? null : smsgStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_TYPE
     *
     * @return the value of STU_MSG.SMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgType() {
        return smsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_TYPE
     *
     * @param smsgType the value for STU_MSG.SMSG_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgType(String smsgType) {
        this.smsgType = smsgType == null ? null : smsgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_MSG.SMSG_GROUP
     *
     * @return the value of STU_MSG.SMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSmsgGroup() {
        return smsgGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_MSG.SMSG_GROUP
     *
     * @param smsgGroup the value for STU_MSG.SMSG_GROUP
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSmsgGroup(String smsgGroup) {
        this.smsgGroup = smsgGroup == null ? null : smsgGroup.trim();
    }
}