package com.great.entity;

import java.util.Date;

public class StuScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.SC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String scUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.SC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer scScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.SC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date scDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String curSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.START_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_SCORE.END_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.SC_UUID
     *
     * @return the value of STU_SCORE.SC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getScUuid() {
        return scUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.SC_UUID
     *
     * @param scUuid the value for STU_SCORE.SC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScUuid(String scUuid) {
        this.scUuid = scUuid == null ? null : scUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.STU_UUID
     *
     * @return the value of STU_SCORE.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.STU_UUID
     *
     * @param stuUuid the value for STU_SCORE.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.SC_SCORE
     *
     * @return the value of STU_SCORE.SC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getScScore() {
        return scScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.SC_SCORE
     *
     * @param scScore the value for STU_SCORE.SC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScScore(Integer scScore) {
        this.scScore = scScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.SC_DATE
     *
     * @return the value of STU_SCORE.SC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getScDate() {
        return scDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.SC_DATE
     *
     * @param scDate the value for STU_SCORE.SC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setScDate(Date scDate) {
        this.scDate = scDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.CUR_SUB
     *
     * @return the value of STU_SCORE.CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getCurSub() {
        return curSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.CUR_SUB
     *
     * @param curSub the value for STU_SCORE.CUR_SUB
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setCurSub(String curSub) {
        this.curSub = curSub == null ? null : curSub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.START_TIME
     *
     * @return the value of STU_SCORE.START_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.START_TIME
     *
     * @param startTime the value for STU_SCORE.START_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_SCORE.END_TIME
     *
     * @return the value of STU_SCORE.END_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_SCORE.END_TIME
     *
     * @param endTime the value for STU_SCORE.END_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

	@Override
	public String toString() {
		return "StuScore [scUuid=" + scUuid + ", stuUuid=" + stuUuid
				+ ", scScore=" + scScore + ", scDate=" + scDate + ", curSub="
				+ curSub + ", startTime=" + startTime + ", endTime=" + endTime
				+ "]";
	}
    
}