package com.great.entity;

public class StuStimulateExam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_STIMULATE_EXAM.SS_EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String ssExamUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_STIMULATE_EXAM.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_STIMULATE_EXAM.SS_EXAM_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer ssExamScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_STIMULATE_EXAM.SS_EXAM_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String ssExamSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STU_STIMULATE_EXAM.SS_EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String ssExamDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_STIMULATE_EXAM.SS_EXAM_UUID
     *
     * @return the value of STU_STIMULATE_EXAM.SS_EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSsExamUuid() {
        return ssExamUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_STIMULATE_EXAM.SS_EXAM_UUID
     *
     * @param ssExamUuid the value for STU_STIMULATE_EXAM.SS_EXAM_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSsExamUuid(String ssExamUuid) {
        this.ssExamUuid = ssExamUuid == null ? null : ssExamUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_STIMULATE_EXAM.STU_UUID
     *
     * @return the value of STU_STIMULATE_EXAM.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_STIMULATE_EXAM.STU_UUID
     *
     * @param stuUuid the value for STU_STIMULATE_EXAM.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_STIMULATE_EXAM.SS_EXAM_SCORE
     *
     * @return the value of STU_STIMULATE_EXAM.SS_EXAM_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSsExamScore() {
        return ssExamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_STIMULATE_EXAM.SS_EXAM_SCORE
     *
     * @param ssExamScore the value for STU_STIMULATE_EXAM.SS_EXAM_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSsExamScore(Integer ssExamScore) {
        this.ssExamScore = ssExamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_STIMULATE_EXAM.SS_EXAM_SUBJECT
     *
     * @return the value of STU_STIMULATE_EXAM.SS_EXAM_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSsExamSubject() {
        return ssExamSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_STIMULATE_EXAM.SS_EXAM_SUBJECT
     *
     * @param ssExamSubject the value for STU_STIMULATE_EXAM.SS_EXAM_SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSsExamSubject(String ssExamSubject) {
        this.ssExamSubject = ssExamSubject == null ? null : ssExamSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STU_STIMULATE_EXAM.SS_EXAM_DATE
     *
     * @return the value of STU_STIMULATE_EXAM.SS_EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSsExamDate() {
        return ssExamDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STU_STIMULATE_EXAM.SS_EXAM_DATE
     *
     * @param ssExamDate the value for STU_STIMULATE_EXAM.SS_EXAM_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSsExamDate(String ssExamDate) {
        this.ssExamDate = ssExamDate == null ? null : ssExamDate.trim();
    }

	@Override
	public String toString() {
		return "StuStimulateExam [ssExamUuid=" + ssExamUuid + ", stuUuid="
				+ stuUuid + ", ssExamScore=" + ssExamScore + ", ssExamSubject="
				+ ssExamSubject + ", ssExamDate=" + ssExamDate + "]";
	}
    
    
}