package com.great.entity;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBJECT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer subNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBJECT.SUB_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String subName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBJECT.SUB_NEED_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer subNeedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBJECT.SUB_NO
     *
     * @return the value of SUBJECT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSubNo() {
        return subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBJECT.SUB_NO
     *
     * @param subNo the value for SUBJECT.SUB_NO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSubNo(Integer subNo) {
        this.subNo = subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBJECT.SUB_NAME
     *
     * @return the value of SUBJECT.SUB_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBJECT.SUB_NAME
     *
     * @param subName the value for SUBJECT.SUB_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSubName(String subName) {
        this.subName = subName == null ? null : subName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBJECT.SUB_NEED_TIME
     *
     * @return the value of SUBJECT.SUB_NEED_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getSubNeedTime() {
        return subNeedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBJECT.SUB_NEED_TIME
     *
     * @param subNeedTime the value for SUBJECT.SUB_NEED_TIME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSubNeedTime(Integer subNeedTime) {
        this.subNeedTime = subNeedTime;
    }
}