package com.great.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Trainer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String schUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer traId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_AGE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Integer traAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private BigDecimal traScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.TRA_HIRE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date traHireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String drivingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_UUID
     *
     * @return the value of TRAINER.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraUuid() {
        return traUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_UUID
     *
     * @param traUuid the value for TRAINER.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraUuid(String traUuid) {
        this.traUuid = traUuid == null ? null : traUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.SCH_UUID
     *
     * @return the value of TRAINER.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getSchUuid() {
        return schUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.SCH_UUID
     *
     * @param schUuid the value for TRAINER.SCH_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setSchUuid(String schUuid) {
        this.schUuid = schUuid == null ? null : schUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_ID
     *
     * @return the value of TRAINER.TRA_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getTraId() {
        return traId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_ID
     *
     * @param traId the value for TRAINER.TRA_ID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraId(Integer traId) {
        this.traId = traId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_NAME
     *
     * @return the value of TRAINER.TRA_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraName() {
        return traName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_NAME
     *
     * @param traName the value for TRAINER.TRA_NAME
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraName(String traName) {
        this.traName = traName == null ? null : traName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_PWD
     *
     * @return the value of TRAINER.TRA_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraPwd() {
        return traPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_PWD
     *
     * @param traPwd the value for TRAINER.TRA_PWD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraPwd(String traPwd) {
        this.traPwd = traPwd == null ? null : traPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_GENDER
     *
     * @return the value of TRAINER.TRA_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraGender() {
        return traGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_GENDER
     *
     * @param traGender the value for TRAINER.TRA_GENDER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraGender(String traGender) {
        this.traGender = traGender == null ? null : traGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_AGE
     *
     * @return the value of TRAINER.TRA_AGE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Integer getTraAge() {
        return traAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_AGE
     *
     * @param traAge the value for TRAINER.TRA_AGE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraAge(Integer traAge) {
        this.traAge = traAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_PHONE
     *
     * @return the value of TRAINER.TRA_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraPhone() {
        return traPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_PHONE
     *
     * @param traPhone the value for TRAINER.TRA_PHONE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraPhone(String traPhone) {
        this.traPhone = traPhone == null ? null : traPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_INTRO
     *
     * @return the value of TRAINER.TRA_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraIntro() {
        return traIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_INTRO
     *
     * @param traIntro the value for TRAINER.TRA_INTRO
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraIntro(String traIntro) {
        this.traIntro = traIntro == null ? null : traIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_SCORE
     *
     * @return the value of TRAINER.TRA_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public BigDecimal getTraScore() {
        return traScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_SCORE
     *
     * @param traScore the value for TRAINER.TRA_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraScore(BigDecimal traScore) {
        this.traScore = traScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.TRA_HIRE_DATE
     *
     * @return the value of TRAINER.TRA_HIRE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getTraHireDate() {
        return traHireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.TRA_HIRE_DATE
     *
     * @param traHireDate the value for TRAINER.TRA_HIRE_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraHireDate(Date traHireDate) {
        this.traHireDate = traHireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.DRIVING_TYPE
     *
     * @return the value of TRAINER.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getDrivingType() {
        return drivingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.DRIVING_TYPE
     *
     * @param drivingType the value for TRAINER.DRIVING_TYPE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setDrivingType(String drivingType) {
        this.drivingType = drivingType == null ? null : drivingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER.LAST_LOGIN_DATE
     *
     * @return the value of TRAINER.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for TRAINER.LAST_LOGIN_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
}