package com.great.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TrainerComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.TC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String tcUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.TC_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String tcComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.TC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date tcDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_COMMENT.TC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private BigDecimal tcScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.TC_UUID
     *
     * @return the value of TRAINER_COMMENT.TC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTcUuid() {
        return tcUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.TC_UUID
     *
     * @param tcUuid the value for TRAINER_COMMENT.TC_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTcUuid(String tcUuid) {
        this.tcUuid = tcUuid == null ? null : tcUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.TRA_UUID
     *
     * @return the value of TRAINER_COMMENT.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraUuid() {
        return traUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.TRA_UUID
     *
     * @param traUuid the value for TRAINER_COMMENT.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraUuid(String traUuid) {
        this.traUuid = traUuid == null ? null : traUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.STU_UUID
     *
     * @return the value of TRAINER_COMMENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.STU_UUID
     *
     * @param stuUuid the value for TRAINER_COMMENT.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.TC_COMMENT
     *
     * @return the value of TRAINER_COMMENT.TC_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTcComment() {
        return tcComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.TC_COMMENT
     *
     * @param tcComment the value for TRAINER_COMMENT.TC_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTcComment(String tcComment) {
        this.tcComment = tcComment == null ? null : tcComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.TC_DATE
     *
     * @return the value of TRAINER_COMMENT.TC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getTcDate() {
        return tcDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.TC_DATE
     *
     * @param tcDate the value for TRAINER_COMMENT.TC_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTcDate(Date tcDate) {
        this.tcDate = tcDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_COMMENT.TC_SCORE
     *
     * @return the value of TRAINER_COMMENT.TC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public BigDecimal getTcScore() {
        return tcScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_COMMENT.TC_SCORE
     *
     * @param tcScore the value for TRAINER_COMMENT.TC_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTcScore(BigDecimal tcScore) {
        this.tcScore = tcScore;
    }
}