package com.great.entity;

import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

public class TrainerStu {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.TRA_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traStuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String traUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private Date graduatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAINER_STU.STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    private String stuStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.TRA_STU_UUID
     *
     * @return the value of TRAINER_STU.TRA_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    
    
    
    
    public String getTraStuUuid() {
        return traStuUuid;
    }

    public TrainerStu(String traStuUuid, String traUuid, String stuUuid,
			Date registerDate, Date graduatedDate, String stuStatus) {
		super();
		this.traStuUuid = traStuUuid;
		this.traUuid = traUuid;
		this.stuUuid = stuUuid;
		this.registerDate = registerDate;
		this.graduatedDate = graduatedDate;
		this.stuStatus = stuStatus;
	}

	public TrainerStu() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.TRA_STU_UUID
     *
     * @param traStuUuid the value for TRAINER_STU.TRA_STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraStuUuid(String traStuUuid) {
        this.traStuUuid = traStuUuid == null ? null : traStuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.TRA_UUID
     *
     * @return the value of TRAINER_STU.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getTraUuid() {
        return traUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.TRA_UUID
     *
     * @param traUuid the value for TRAINER_STU.TRA_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setTraUuid(String traUuid) {
        this.traUuid = traUuid == null ? null : traUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.STU_UUID
     *
     * @return the value of TRAINER_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuUuid() {
        return stuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.STU_UUID
     *
     * @param stuUuid the value for TRAINER_STU.STU_UUID
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuUuid(String stuUuid) {
        this.stuUuid = stuUuid == null ? null : stuUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.REGISTER_DATE
     *
     * @return the value of TRAINER_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.REGISTER_DATE
     *
     * @param registerDate the value for TRAINER_STU.REGISTER_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.GRADUATED_DATE
     *
     * @return the value of TRAINER_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public Date getGraduatedDate() {
        return graduatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.GRADUATED_DATE
     *
     * @param graduatedDate the value for TRAINER_STU.GRADUATED_DATE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setGraduatedDate(Date graduatedDate) {
        this.graduatedDate = graduatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAINER_STU.STU_STATUS
     *
     * @return the value of TRAINER_STU.STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public String getStuStatus() {
        return stuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAINER_STU.STU_STATUS
     *
     * @param stuStatus the value for TRAINER_STU.STU_STATUS
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    public void setStuStatus(String stuStatus) {
        this.stuStatus = stuStatus == null ? null : stuStatus.trim();
    }

	@Override
	public String toString() {
		return "TrainerStu [traStuUuid=" + traStuUuid + ", traUuid=" + traUuid
				+ ", stuUuid=" + stuUuid + ", registerDate=" + registerDate
				+ ", graduatedDate=" + graduatedDate + ", stuStatus="
				+ stuStatus + "]";
	}
 
   
  
    
    
}