package com.great.dao;

import com.great.entity.AccountChar;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface AccountCharMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_CHAR
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(@Param("admUuid") String admUuid, @Param("charNo") Integer charNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_CHAR
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(AccountChar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_CHAR
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(AccountChar record);
    
    int delByAdmUuId(String admUuId);
}