package com.great.dao;

import com.great.entity.AdmCharacter;

public interface AdmCharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(Integer charNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(AdmCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(AdmCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    AdmCharacter selectByPrimaryKey(Integer charNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(AdmCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADM_CHARACTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(AdmCharacter record);
}