package com.great.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.Authority;
@Repository
public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(Integer authNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    Authority selectByPrimaryKey(Integer authNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(Authority record);
    
    List<Map<String, String>> getMenuInfo(int admId);
}