package com.great.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.CardTimeRecord;
@Repository
public interface CardTimeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String ctrUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(CardTimeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(CardTimeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    CardTimeRecord selectByPrimaryKey(String ctrUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(CardTimeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_TIME_RECORD
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(CardTimeRecord record);
    
    public List<Map<String, String>> selectFirstSubTime(String stuUuid);
    
    public List<Map<String, String>> selectForthSubTime(String stuUuid);
    
    public int insertCartTime(CardTimeRecord rec);
}