package com.great.dao;


import java.awt.List;
import java.util.ArrayList;


import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.CenterAnnouncement;
@Repository
public interface CenterAnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(Integer caNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(CenterAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(CenterAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    CenterAnnouncement selectByPrimaryKey(Integer caNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(CenterAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(CenterAnnouncement record);
    
    public CenterAnnouncement getAnnouncement();//获取运管最近的一次公告

   public ArrayList<CenterAnnouncement> getAllAnnouncement();

    
    java.util.List<Map<String, String>> getAnnoInfo();
    
    int delAnnoByTitle(String title);

}