package com.great.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.CenterAdmin;
@Repository
public interface CenterAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String admUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(CenterAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(CenterAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    CenterAdmin selectByPrimaryKey(String admUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(CenterAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTER_ADMIN
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(CenterAdmin record);
    
    CenterAdmin selectById(int admId);
    
    ArrayList<CenterAdmin> selectAllAdmin();
    
    List<Map<String, String>> selectAllAdmChar();
    
    Map<String, String> selectAdminInfo(String admUuid);
}