package com.great.dao;

import java.util.ArrayList;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.ExamRegister;
@Repository
public interface ExamRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String regExamUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(ExamRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(ExamRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    ExamRegister selectByPrimaryKey(String regExamUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(ExamRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXAM_REGISTER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(ExamRegister record);
    
    int delByStuIdentityExamUuid(Map<String, String> map);
    
    ExamRegister selectExamRegisterByStuIdentityExamUuid(Map<String, String> map);
    
    ExamRegister selectExamRegisterByStuIdentity(String stuIdentity);
    
    ArrayList<ExamRegister> getRegistedStudent();
    
}