package com.great.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.great.entity.FalseQuestion;
import com.great.entity.Question;
@Repository
public interface FalseQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String falseQuesUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(FalseQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(FalseQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    FalseQuestion selectByPrimaryKey(String falseQuesUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(FalseQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FALSE_QUESTION
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(FalseQuestion record);
    
    public int insertFalse(String uuid, String qno, String stuUuid);
     
    public List<FalseQuestion> getFalseQNo(String stuUuid);
    
    public Question getFalseQuestion(String qno);
    
    public int delFalseQNo(String qno);
}