package com.great.dao;

import java.util.ArrayList;

import org.springframework.stereotype.Repository;

import com.great.entity.PracticeNoRec;
@Repository
public interface PracticeNoRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRACTICE_NO_REC
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(PracticeNoRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRACTICE_NO_REC
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(PracticeNoRec record);
    
    public String getQuestionNo(String stuUuid, String subject);
    
    public int recNo(String qno, String stuUuid, String subject);
    
    public ArrayList<PracticeNoRec> checkQNo(String stuUuid);
    
    public int addSubFirst(String stuUuid);
    
    public int addSubForth(String stuUuid);
}