package com.great.dao;

import java.util.ArrayList;

import org.springframework.stereotype.Repository;

import com.great.entity.SchAnnouncement;
@Repository
public interface SchAnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String anUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(SchAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(SchAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    SchAnnouncement selectByPrimaryKey(String anUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(SchAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCH_ANNOUNCEMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(SchAnnouncement record);

    
    ArrayList<SchAnnouncement> getAllAnnouncement(SchAnnouncement announcement);
    ArrayList<SchAnnouncement> selectByPrimaryKeySelective(SchAnnouncement announcement);

    
    //同过学生的id获取相应的驾校最近的一条消息
    public SchAnnouncement getAnnouncementByStuId(String stuId);
    
    //获取所有的驾校公告
    public ArrayList<SchAnnouncement> getAllAnnouncements(String stuUuid);

}