package com.great.dao;

import java.util.ArrayList;

import org.springframework.stereotype.Repository;

import com.great.entity.DriverSchool;
import com.great.entity.SchoolStu;
@Repository
public interface SchoolStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String schStuUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(SchoolStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(SchoolStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    SchoolStu selectByPrimaryKey(String schStuUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(SchoolStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(SchoolStu record);
    
    ArrayList<SchoolStu> getStuIdBySchId(DriverSchool driverSchool);
    
    public String getSchoolUuidByStuUuid(String stuUuid);
    
  
}