package com.great.dao;

import java.util.ArrayList;



import org.springframework.stereotype.Repository;





import com.great.entity.MsgInfo;
import com.great.entity.SchoolMsg;
@Repository
public interface SchoolMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String scmsgUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(SchoolMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(SchoolMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    SchoolMsg selectByPrimaryKey(String scmsgUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(SchoolMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_MSG
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(SchoolMsg record);

    
    ArrayList<MsgInfo> getSchoolMsgs(SchoolMsg msg);

}