package com.great.dao;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;

import org.springframework.stereotype.Repository;



import com.great.entity.SchoolComment;
@Repository
public interface SchoolCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String sctUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(SchoolComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(SchoolComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    SchoolComment selectByPrimaryKey(String sctUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(SchoolComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(SchoolComment record);

    public List<Map<String, String>>  showAppraiseByStuUuid(String StuUuid);
    
    //查询总分
    public int selectSumScore(String stuUuid);
    //查询评论个数
    public int selectConut(String stuUuid);
    //查看学生是否评价过
    public SchoolComment selectSchoolCommentByStuUuid(String stuUuid);
    ArrayList<SchoolComment> getAllDiscuss();
}