package com.great.dao;

import com.great.entity.StimulatAnswer;

public interface StimulatAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String sAnsUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(StimulatAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(StimulatAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    StimulatAnswer selectByPrimaryKey(String sAnsUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(StimulatAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STIMULAT_ANSWER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(StimulatAnswer record);
}