package com.great.dao;

import java.util.ArrayList;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.Student;
@Repository
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String stuUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    Student selectByPrimaryKey(String stuUuid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    ArrayList<Student> getAllStudent();
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT 
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(Student record);
    
   public Student selectByIdentity(String stuIdentity);//通过身份证查询
   
   public Student studentLogin(Student student);//学生登陆
   
   public Student checkStuId(Student student);//检查学生id
   
   public Student checkPwd(Map<String, String>map);//修改密码检验旧密码是否正确
   
   public int updateStudentPwd(Map<String, String>map);//修改密码
   
   public Student getNewUuid();//学生注册获取uuid插入到sch_stu表
   
   public int insertMyStudent(Student student);
}