package com.great.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.StuStimulateExam;
@Repository
public interface StuStimulateExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String ssExamUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(StuStimulateExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(StuStimulateExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    StuStimulateExam selectByPrimaryKey(String ssExamUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(StuStimulateExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_STIMULATE_EXAM
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(StuStimulateExam record);
    
    public List<Map<String, String>> getMocExamScore(String stuUuid);
    
    public int insertScore(StuStimulateExam stumoc);
}