package com.great.dao;

import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.StuExamInfo;
import com.great.entity.StuScore;
@Repository
public interface StuScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String scUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    StuScore selectByPrimaryKey(String scUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(StuScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STU_SCORE
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(StuScore record);
    
    public StuExamInfo selectByStuUuid(String stuUuid);
    
    public StuScore selectByStuUuidExamDate(Map<String, Object> map);
}