package com.great.dao;

import org.springframework.stereotype.Repository;

import com.great.entity.Subject;
@Repository
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(Integer subNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    Subject selectByPrimaryKey(Integer subNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBJECT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(Subject record);
    
    Subject getSubTime(Subject record);
}