package com.great.dao;

import java.util.ArrayList;
import java.util.List;



import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.Student;
import com.great.entity.TrainerComment;
import com.great.entity.TrainerStu;

@Repository
public interface TrainerStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String traStuUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(TrainerStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(TrainerStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
   List<TrainerStu> selectByPrimaryKey(String traStuUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(TrainerStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_STU
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(TrainerStu record);
    
    public Student showAllStudents(String stu_uuid);
    
    public List<Map<String, String>> showStuTime(List<Student> student);
    
    public String getTrainerUuidByStuUuid(String stu_uuid);
    
    public ArrayList<TrainerStu> checkSetedStudent();
    
    

}