package com.great.dao;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import org.springframework.stereotype.Repository;

import com.great.entity.Trainer;
import com.great.entity.VerifyPwd;

@Repository
public interface TrainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String traUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(Trainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(Trainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    Trainer selectByPrimaryKey(String traUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(Trainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(Trainer record);
    
    ArrayList<Trainer> getAllTrainers(Trainer trainer);
	
	public Trainer  loginVerify(Trainer trainer);
	
    public int  updateLoginTime(Trainer trainer);
    
    public Trainer selectTrainer(VerifyPwd pwd); 
   
    public int updateTrainerPwd(VerifyPwd pwd);
    
    public int updateTrainerScore(Map<String, Object> map );
	
   public List<Trainer> getTrainersBySchUuid(String schUuid);
}