package com.great.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.great.entity.TrainerComment;
import com.great.entity.UpdateTrainerMsg;

@Repository
public interface TrainerCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int deleteByPrimaryKey(String tcUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insert(TrainerComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int insertSelective(TrainerComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    TrainerComment selectByPrimaryKey(String tcUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKeySelective(TrainerComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRAINER_COMMENT
     *
     * @mbggenerated Tue Sep 26 17:46:16 CST 2017
     */
    int updateByPrimaryKey(TrainerComment record);
    
    
    public List<Map<String, String>> showAppraise(String traUuid);
    
    public int updateTrainerMsg(UpdateTrainerMsg msg);
    
    //显示教练的评价通过学生id
    public List<Map<String, String>>  showAppraiseByStuUuid(String StuUuid);
    //查询总分
    public int selectSumScore(String stuUuid);
    //查询评论个数
    public int selectConut(String stuUuid);
    //查看学生是否评价过
    public TrainerComment selecTrainerCommentByStuUuid(String stuUuid);
    
}